config/routes.rb
Rails.application.routes.draw do

  get 'cart/index'

  get 'cart/show'

  get 'cart/create'

  get 'cart/new'

  get 'cart/register'

  get 'search/index'

  get 'search/result'

  devise_for :beta_grocery_customers
  resource :homepage
  resource :cart
  get 'homepage/index'
  get 'homepage/show'
  post 'homepage/create'
  root to: 'homepage#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beta_grocery.rb
class BetaGrocery < ApplicationRecord
end

app/models/beta_grocery_customer.rb
class BetaGroceryCustomer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @list_items = session[:items]
  end

  def show
  end

  def create
  end

  def register
    session[:items] = nil
    redirect_to root_path
  end

  def new

  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index

    @data = BetaGroceryCustomer.all

    @all_groceries = BetaGrocery.all

  end

  def show
    @item = params[:id]

    @show = BetaGrocery.find(@item)


  end

  def create
    id = params[:show][:id]
    total = params[:quantity]
    (session[:items] ||= []) << ["item" => id, "total" => total]
    redirect_to homepage_index_path
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def result
    @result = BetaGrocery.where('lower(grocery_name) LIKE :search', search: "%#{params[:q]}%")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cart/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/cart/index.html.erb
<div class="container">
  <div class="row">

    <h2>Your cart</h2>

    <% if !@list_items.nil? then %>
        <ul class="list-group">
          <% @list_items.each do |list| %>
              <% list.each do |down| %>
                  <li class="list-group-item">
                    <%= BetaGrocery.find(down["item"]).grocery_name %>
                    x<%= down["total"] %>


                    | Price :
                    RM <%= number_with_precision((BetaGrocery.find(down["item"]).grocery_price.to_f * down["total"].to_i), precision: 2) %>
                  </li>


              <% end %>
          <% end %>

        </ul>


        <form action="<%= cart_register_path %>">
          <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_I5bDfH3sC9x6eEpyjYYfayFw"
          data-amount="999"
          data-name="Market"
          data-description="Widget"
          data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
          data-locale="auto"
          data-currency="myr">
          </script>
        </form>
    <% else %>
        <p>Your cart is empty</p>
    <% end %>


  </div>
</div>

app/views/cart/new.html.erb
<h1>Cart#new</h1>
<p>Find me in app/views/cart/new.html.erb</p>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

app/views/homepage/index.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h2>Groceries</h2>

        <% if current_beta_grocery_customer.nil? %>

        <% else %>
          <p>Welcome, <%= current_beta_grocery_customer.email %></p>
        <% end %>

        <p>We provide you with the freshest groceries in stock and with good quality and price.</p>
        <% @all_groceries.each do |grocery| %>

            <div class="col-md-4 text-center">
              <div class="thumbnail" style="height: 400px;">
                <img src="<%= grocery.grocery_image %>" alt="">
                <hr>
                <h3><%= grocery.grocery_name %></h3>
                <em>RM <%= grocery.grocery_price %></em>
                <br>
                <%= link_to "Buy Now", homepage_show_path(:id => grocery.id), class: "btn btn-primary" %>


              </div>


            </div>


        <% end %>


      </div>
    </div>
  </div>
</section>


<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
  </div>
  <!-- /.container -->
</footer>

app/views/homepage/show.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h3><%=	 @show.grocery_name %></h3>

      <div class="thumbnail" >
        <img src="<%= @show.grocery_image %>" alt="" width="200px">


        <%= form_for :homepage, url: homepage_create_path, method: :post, html: {class: "nifty_form"} do |f| %>
            <p>Total</p>
            <%= hidden_field(:show, :id) %>
            <input type="text" placeholder="1" name="quantity">
            <%= f.submit "Buy" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Market</title>
  <%= csrf_meta_tags %>

  <!--<%= stylesheet_link_tag 'application', media: 'all' %>-->
  <!--<%= javascript_include_tag 'application' %>-->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>


    header {
      padding: 154px 0 100px;
    }

    @media (min-width: 992px) {
      header {
        padding: 156px 0 100px;
      }
    }

    section {
      padding: 150px 0;
    }

    .search-container {
      float: right;
    }

    .search-container button {
      float: right;
      padding: 6px 10px;
      margin-top: 8px;
      margin-right: 16px;
      background: #ddd;
      font-size: 17px;
      border: none;
      cursor: pointer;
    }

    .search-container button:hover {
      background: #ccc;
    }

    .search-container input[type=text] {
      padding: 6px;
      margin-top: 8px;
      font-size: 17px;
      border: none;
    }

    .cart {
      float: right;
      color: white;
      padding-top: 13px;
    }

  </style>
</head>


<body id="page-top">

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Market</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>

      <% if !current_beta_grocery_customer %>
          <li><a href="/beta_grocery_customers/sign_up">Register</a></li>
          <li><a href="/beta_grocery_customers/sign_in">Login</a></li>
      <% else %>
          <li><%= link_to "Sign out", destroy_beta_grocery_customer_session_path %></li>
      <% end %>
    </ul>
    <div class="search-container">
      <%= link_to cart_index_path, class: "cart" do %>
          <% if current_beta_grocery_customer.nil? %>

          <% else %>
              <% if session[:items] %>
                  Cart: <span class="badge"><%= session[:items].length %></span>

              <% else %>
                  Cart: 0
              <% end %>
          <% end %>

      <% end %>

      <div class="input-group">
        <%= form_tag("/search/result", method: "get") do %>
            <input type="text" placeholder="Search.." name="q">
            <button type="submit"><i class="fa fa-search"></i></button>
        <% end %>
      </div><!-- /input-group -->
    </div>

  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</body>
</html>

app/views/search/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Search#index</h1>
      <p>Find me in app/views/search/index.html.erb</p>


      <%= form_tag("/search/result", method: "get") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
      <% end %>

    </div>
  </div>
</div>

<hr>

<div class="container">
  <div class="row"></div>
</div>

app/views/search/result.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Search#result</h1>
      <p>Find me in app/views/search/result.html.erb</p>

      <h3>Result is</h3>
      <% @result.each do |grocery| %>
          <div class="thumbnail col-md-4 text-center" style="height: 400px;">

            <img src="<%= grocery.grocery_image %>" alt="">
            <hr>
            <h3><%= grocery.grocery_name %></h3>
            <em>RM <%= grocery.grocery_price %></em>
            <br>
            <button class="btn btn-primary">Buy Now</button>
          </div>
      <% end %>
    </div>
  </div>
</div>